typography_spectrum: 0.6713472995907068
color:
  brandStrength: 0.36996143823489547
  lightness: 0.3713204301893711
  saturation: 0.7737166911829263
  rhythmicContrast: 0.13236981071531773
  brandColors:
    - '#17BEBB'
    - '#2E282A'
    - '#CD5334'
    - '#EDB88B'
    - '#FAD8D6'
layout_spectrum: 0.33720351941883564
name: Vital Branding
navigation:
  - name: Company Website
    url: 'https://vtlbranding.com/'
    type: external
title: Marketing. Simplified.
description: We make it easy. We make it direct. We make it Vital.
